import csv

# Your data as a list of dictionaries
data = [
    {"Title": "NASA Launches New Mars Rover on Historic Mission", "Text": "NASA's new Mars rover, Perseverance, has successfully landed on the red planet and is set to explore the Martian surface in search of signs of past life.", "label": "1"},
    {"Title": "Global Markets Rally as Inflation Slows", "Text": "Stock markets around the world saw gains today after data showed a decline in inflation across major economies.", "label": "1"},
    {"Title": "WHO Approves New Malaria Vaccine for Widespread Use", "Text": "The World Health Organization has approved a new malaria vaccine, marking a significant step toward eradicating the disease in Africa.", "label": "1"},
    {"Title": "Apple Unveils iPhone 16 with AI-Powered Features", "Text": "Apple introduced the iPhone 16 at its annual event, showcasing AI integration in its camera and Siri assistant.", "label": "1"},
    {"Title": "India Achieves Record Wheat Production in 2025", "Text": "The Ministry of Agriculture announced India’s highest-ever wheat yield this season, boosting food security.", "label": "1"},
    {"Title": "UN Calls for Ceasefire in Ongoing Middle East Conflict", "Text": "The United Nations has urged both sides in the conflict to halt violence and begin peace negotiations.", "label": "1"},
    {"Title": "Germany to Phase Out Coal by 2030 in Green Deal", "Text": "As part of its climate goals, Germany will shut down all coal-fired power plants by 2030, replacing them with renewable sources.", "label": "1"},
    {"Title": "COVID-19 Booster Shots Recommended for Seniors", "Text": "Health agencies now advise all adults over 60 to get booster shots amid rising infection rates of the new COVID-19 variant.", "label": "1"},
    {"Title": "Olympic Games Conclude with Record-Breaking Performances", "Text": "The 2024 Olympics ended in Paris with athletes setting new records in track, swimming, and gymnastics.", "label": "1"},
    {"Title": "Electric Vehicles Outsell Petrol Cars in Norway", "Text": "Norway has become the first country where electric vehicle sales have surpassed petrol car purchases.", "label": "1"},
    {"Title": "Facebook Parent Meta Expands into Metaverse Education", "Text": "Meta announced a new initiative to build virtual classrooms, offering immersive education experiences.", "label": "1"},
    {"Title": "China Launches New Weather Satellite for Global Monitoring", "Text": "China successfully deployed a satellite to improve global weather forecasting and disaster response.", "label": "1"},
    {"Title": "UK Votes to Increase Minimum Wage Starting July", "Text": "The UK Parliament approved a bill raising the national minimum wage to support working-class families.", "label": "1"},
    {"Title": "Russia and US Agree to Resume Arms Control Talks", "Text": "Diplomats from both nations confirmed plans to revive arms control discussions halted last year.", "label": "1"},
    {"Title": " Amazon to Open 10 New Warehouses in India", "Text": "Amazon announced the expansion of its logistics network in India, aiming to speed up deliveries.", "label": "1"},
    {"Title": "Japan Passes Law to Encourage Remote Work Culture", "Text": "Japan's parliament approved legislation supporting flexible work hours and remote jobs post-pandemic.", "label": "1"},
    {"Title": "Australia Declares National Emergency Over Wildfires", "Text": "Wildfires across New South Wales have prompted the government to declare a state of emergency.", "label": "1"},
    {"Title": "Brazil Launches National Reforestation Plan", "Text": "The Brazilian government introduced a 10-year plan to restore deforested regions of the Amazon rainforest.", "label": "1"},
    {"Title": "New Study Links Air Pollution to Cognitive Decline", "Text": "A Harvard study reveals long-term exposure to fine particles in polluted air affects brain health.", "label": "1"},
    {"Title": "Tesla Introduces Affordable Model A for Developing Markets", "Text": "Tesla has unveiled a low-cost EV designed for emerging markets, starting with production in India.", "label": "1"},
    {"Title": "Google Introduces AI Search Upgrades at I/O Conference", "Text": "Google announced major updates to its search engine powered by generative AI, enhancing user experience.", "label": "1"},
    {"Title": "South Korea Reports Strong Q1 Economic Growth", "Text": "Driven by tech exports and domestic demand, South Korea’s economy grew 4.2% in the first quarter.", "label": "1"},
    {"Title": "Scientists Detect Water Vapor on Distant Exoplanet", "Text": "Astronomers have found signs of water vapor on a planet 120 light-years away, increasing hope for life.", "label": "1"},
    {"Title": "World Bank Predicts 3.5% Global Growth in 2025", "Text": "The World Bank projects steady global economic growth supported by digital transformation and recovery efforts.", "label": "1"},
    {"Title": "France Bans Single-Use Plastics in Retail Stores", "Text": "France has become the first EU country to completely ban single-use plastic packaging in supermarkets.", "label": "1"},
    {"Title": "Pfizer Reports Success in Universal Flu Vaccine Trial", "Text": "Pfizer’s new universal flu vaccine showed 85% effectiveness in preventing multiple flu strains.", "label": "1"},
    {"Title": "Africa’s Largest Solar Farm Opens in Kenya", "Text": "A solar project in northern Kenya is now providing electricity to over a million homes.", "label": "1"},
    {"Title": "Microsoft Invests $2 Billion in Indian AI Startups", "Text": "Microsoft will fund AI-driven startups across India to boost local innovation and talent development.", "label": "1"},
    {"Title": "Canada Tightens Immigration Rules for Tech Workers", "Text": "In response to housing shortages, Canada has revised its immigration program for tech professionals.", "label": "1"},
    {"Title": "Italy’s Venice Implements Tourist Entry Fee", "Text": "Tourists visiting Venice must now pay a €5 entry fee as part of preservation efforts.", "label": "1"},
    {"Title": "Netflix Releases First Fully AI-Generated Series", "Text": "Netflix’s new animated series, created entirely with AI tools, pushes the boundaries of content creation.", "label": "1"},
    {"Title": "Global Cybersecurity Summit Begins in Geneva", "Text": "Leaders and tech giants convene in Geneva to discuss strategies against rising cyber threats.", "label": "1"},
    {"Title": "Researchers Create Biodegradable Smartphone Case", "Text": "A team at MIT developed a phone case made of plant-based materials that degrades in 60 days.", "label": "1"},
    {"Title": "Ukraine Receives Additional Aid Package from EU", "Text": "The European Union approved a €12 billion aid package for Ukraine to support rebuilding efforts.", "label": "1"},
    {"Title": "Dubai Opens World’s Tallest Vertical Farm", "Text": "The UAE launched the largest vertical farm, aiming to ensure food security in arid regions.", "label": "1"},
    {"Title": "AI Startup Raises $100 Million to Revolutionize Education", "Text": "EdTech startup EduAI has secured funding to develop personalized AI learning systems.", "label": "1"},
    {"Title": "Researchers Discover New Coral Species in Pacific Ocean", "Text": "Marine biologists have identified a previously unknown coral species during an expedition near Fiji.", "label": "1"},
    {"Title": "Vaccination Campaign Begins After Measles Outbreak in Europe", "Text": "Several EU countries have launched emergency vaccination drives following a rise in measles cases.", "label": "1"},
    {"Title": "US Senate Approves Climate Resilience Bill", "Text": "The bill will allocate funds for disaster prevention, infrastructure upgrades, and emission reduction.", "label": "1"},
    {"Title": "Saudi Arabia Plans $500 Billion Smart City", "Text": "NEOM, Saudi Arabia’s futuristic city project, is gaining momentum with new infrastructure announcements.", "label": "1"},
    {"Title": "Twitter Rolls Out New Safety Features to Curb Abuse", "Text": "Twitter now lets users limit replies, filter content, and block offensive language more effectively.", "label": "1"},
    {"Title": "Philippines Declares State of Calamity After Typhoon", "Text": "A powerful typhoon hit central Philippines, prompting emergency aid and rescue operations.", "label": "1"},
    {"Title": "Singapore Launches AI Ethics Framework for Businesses", "Text": "The new guidelines aim to ensure fairness and transparency in AI deployment across industries.", "label": "1"},
    {"Title": "Argentina’s Economy Shows Signs of Stabilization", "Text": "Inflation rates dropped for the third month in a row, boosting investor confidence in Argentina.", "label": "1"},
    {"Title": "UK Scientists Create Battery That Charges in 10 Minutes", "Text": "A University of Oxford team developed a lithium-ion battery that could reduce EV charging time drastically.", "label": "1"},
    {"Title": "Ireland Legalizes Assisted Dying for Terminally Ill Patients", "Text": "Ireland’s parliament passed a controversial law allowing terminal patients to choose assisted death.", "label": "1"},
    {"Title": "AI Detects Early Signs of Alzheimer’s from Speech Patterns", "Text": "Researchers developed an AI model that can predict Alzheimer’s risk from simple speech tests.", "label": "1"},
    {"Title": "Vietnam Emerges as Southeast Asia’s Tech Hub", "Text": "With foreign investment surging, Vietnam is becoming a regional center for software development.", "label": "1"},
    {"Title": "NASA Plans Moon Base Construction by 2030", "Text": "NASA’s Artemis program includes a permanent base on the moon, intended to support deep space missions.", "label": "1"},
    {"Title": "Zimbabwe Introduces Gold-Backed Digital Currency", "Text": "Zimbabwe’s central bank launched a digital currency tied to gold to stabilize its economy.", "label": "1"},
    {"Title": "NASA Discovers Water Ice on the Moon", "Text": "NASA scientists have confirmed the presence of water ice on the moon's surface near its poles, a breakthrough that could support future lunar missions.", "label": "1"},
    {"Title": "ISRO Launches Cartosat-3 Successfully", "Text": "India's space agency ISRO launched Cartosat-3, a high-resolution imaging satellite, to bolster its earth observation capabilities.", "label": "1"},
    {"Title": "NASA's James Webb Telescope Reaches Orbit", "Text": "The James Webb Space Telescope has successfully reached its orbit and is preparing for a deep-space exploration mission beyond the solar system.", "label": "1"},
    {"Title": "SpaceX Launches 60 Starlink Satellites", "Text": "Elon Musk's SpaceX launched 60 additional satellites for its Starlink project aimed at providing global internet access.", "label": "1"},
    {"Title": "NASA and ESA Team Up for Mars Sample Return", "Text": "In a historic collaboration, NASA and the European Space Agency will work together to retrieve soil samples from Mars for the first time.", "label": "1"},
    {"Title": "Chandrayaan-3 Successfully Lands on the Moon", "Text": "India's Chandrayaan-3 mission successfully landed near the Moon's south pole, making India the fourth country to achieve this feat.", "label": "1"},
    {"Title": "NASA's Perseverance Rover Finds Ancient Riverbed", "Text": "NASA's Perseverance rover discovered sediment patterns indicating the presence of an ancient Martian river.", "label": "1"},
    {"Title": "ISRO to Launch Aditya-L1 Solar Mission", "Text": "ISRO is preparing to launch Aditya-L1, its first mission to study the Sun, expected to provide valuable data on solar activity.", "label": "1"},
    {"Title": "NASA Tests New Moon Habitat Design", "Text": "NASA engineers have successfully tested a new prototype lunar habitat designed for long-term human stays on the Moon.", "label": "1"},
    {"Title": "SpaceX Crew-7 Mission Docks at ISS", "Text": "The SpaceX Crew-7 mission safely arrived at the International Space Station, delivering four astronauts for a six-month research mission.", "label": "1"},
    {"Title": "NASA Unveils Artemis II Crew Members", "Text": "NASA has announced the four astronauts who will participate in Artemis II, the first crewed mission to orbit the Moon in over 50 years.", "label": "1"},
    {"Title": "ISRO Successfully Deploys NavIC Satellite", "Text": "The Indian Space Research Organisation successfully launched a NavIC navigation satellite, enhancing India’s regional positioning system.", "label": "1"},
    {"Title": "NASA’s Hubble Telescope Spots Rare Supernova", "Text": "NASA’s Hubble Space Telescope has captured images of a rare Type Iax supernova, offering new insights into stellar evolution.", "label": "1"},
    {"Title": "SpaceX Falcon Heavy Lifts Off with Military Satellite", "Text": "SpaceX's Falcon Heavy rocket carried a classified military satellite into orbit, marking another milestone in private-public space collaboration.", "label": "1"},
    {"Title": "ISRO Begins Testing for Gaganyaan Human Mission", "Text": "ISRO has begun astronaut training and system testing for its upcoming Gaganyaan mission, India’s first manned space flight.", "label": "1"},
    {"Title": "NASA’s Ingenuity Helicopter Completes 50th Flight", "Text": "NASA's Mars helicopter, Ingenuity, has completed its 50th successful flight, far exceeding original expectations.", "label": "1"},
    {"Title": "ESA Approves Funding for Jupiter Icy Moons Explorer", "Text": "The European Space Agency approved funding for its JUICE mission to explore Jupiter's largest moons, including Europa and Ganymede.", "label": "1"},
    {"Title": "NASA Satellites Monitor Climate Change in Arctic", "Text": "NASA’s Earth-observing satellites are monitoring rapid ice loss in the Arctic, providing critical data for climate scientists.", "label": "1"},
    {"Title": "Blue Origin Announces Next Suborbital Flight Schedule", "Text": "Blue Origin confirmed its next suborbital space tourism flight will take place next month, featuring six civilian astronauts.", "label": "1"},
    {"Title": "NASA Collaborates with Japan on Lunar Gateway", "Text": "NASA and JAXA have signed an agreement to jointly develop modules for the upcoming Lunar Gateway space station orbiting the Moon.", "label": "1"},
]

# Write to CSV file
with open("news_articles.csv", mode="w", newline="", encoding="utf-8") as file:
    writer = csv.DictWriter(file, fieldnames=["Title", "Text", "label"])
    writer.writeheader()
    writer.writerows(data)

print("CSV file 'news_articles.csv' created successfully.")
